# GitHub Sponsors - Primary funding method
# No fees for open source projects, integrated with GitHub
github: CMGeorge

# Uncomment and add your usernames if you want additional options:
# patreon: your_patreon_username
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_buymeacoffee_username
# custom: ['https://paypal.me/YourPayPalUsername']
