# These are supported funding model platforms
# Uncomment and add your usernames to enable donation options

github: CMGeorge  # GitHub Sponsors (set up at github.com/sponsors/CMGeorge)
# patreon: your_patreon_username
# open_collective: your_open_collective
# ko_fi: your_kofi_username
# buy_me_a_coffee: your_buymeacoffee_username
# custom: ['https://paypal.me/YourPayPalUsername']
