---
# Bug related labels
- name: bug
  color: d73a4a
  description: Something isn't working

- name: critical
  color: b60205
  description: Critical bug requiring immediate attention

# Enhancement related labels
- name: enhancement
  color: a2eeef
  description: New feature or request

- name: feature-request
  color: 0e8a16
  description: Request for new functionality

# Documentation labels
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

# Workflow labels
- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file

- name: github-actions
  color: 2188ff
  description: Pull requests that update GitHub Actions

- name: python
  color: 3776ab
  description: Python related changes

# Review labels
- name: needs-review
  color: fbca04
  description: Needs review from maintainer

- name: needs-testing
  color: fef2c0
  description: Needs testing with real API

- name: work-in-progress
  color: ededed
  description: Work in progress

# Status labels
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: help-wanted
  color: 008672
  description: Extra attention is needed

- name: good-first-issue
  color: 7057ff
  description: Good for newcomers

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: question
  color: d876e3
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on

# Component labels
- name: api
  color: c2e0c6
  description: Related to API client

- name: sensor
  color: bfdadc
  description: Related to sensor platform

- name: binary-sensor
  color: bfd4f2
  description: Related to binary sensor platform

- name: config-flow
  color: d4c5f9
  description: Related to configuration flow

- name: coordinator
  color: f9c5d4
  description: Related to data coordinator
