# Example Home Assistant configuration for SolarGuardian integration
# This file shows how the integration would appear in your configuration

# The integration is configured via the UI, not YAML
# Go to Settings > Devices & Services > Add Integration > Search for "SolarGuardian"

# Example automation using SolarGuardian sensors
automation:
  - alias: "Solar Power Alert"
    description: "Alert when solar power generation is low during daylight hours"
    trigger:
      - platform: numeric_state
        entity_id: sensor.device060801_pv_power
        below: 100
        for:
          minutes: 30
    condition:
      - condition: sun
        after: sunrise
        before: sunset
    action:
      - service: notify.mobile_app_your_phone
        data:
          title: "Solar Generation Low"
          message: "Solar power generation is only {{ states('sensor.device060801_pv_power') }}W"

  - alias: "Battery Low Warning"
    description: "Warning when battery SOC is low"
    trigger:
      - platform: numeric_state
        entity_id: sensor.device060801_battery_state_of_charge
        below: 20
    action:
      - service: notify.mobile_app_your_phone
        data:
          title: "Battery Low"
          message: "Battery charge is at {{ states('sensor.device060801_battery_state_of_charge') }}%"

  - alias: "Device Offline Alert"
    description: "Alert when solar device goes offline"
    trigger:
      - platform: state
        entity_id: binary_sensor.device060801_online
        to: "off"
        for:
          minutes: 5
    action:
      - service: notify.mobile_app_your_phone
        data:
          title: "Solar Device Offline"
          message: "Solar device {{ trigger.to_state.attributes.friendly_name }} is offline"

# Example template sensors for energy dashboard
template:
  - sensor:
      - name: "Daily Solar Production"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.device060801_generated_energy_today') | float }}"
        
      - name: "Total Solar Production"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.device060801_generated_energy_total') | float }}"

# Energy dashboard configuration
energy:
  sources:
    - type: solar
      stat_energy_from: sensor.daily_solar_production