test_connection:
  name: Test API Connection
  description: Test the connection to the SolarGuardian API and provide diagnostic information
  fields:
    verbose:
      name: Verbose Output
      description: Include detailed diagnostic information in the log
      default: false
      selector:
        boolean:

get_diagnostics:
  name: Get Diagnostics
  description: Get diagnostic information about the SolarGuardian integration

reset_latest_data:
  name: Reset Latest Data Fetching
  description: Re-enable latest data fetching if it was disabled due to repeated failures