name: Manage Labels

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/labels.yml"

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
