name: Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov aiohttp python-dotenv
          
      - name: Run unit tests
        run: |
          python -m pytest tests/unit/ -v --cov=custom_components/solarguardian --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run manually
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio aiohttp python-dotenv

      - name: Run integration tests (if credentials available)
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          if [ -n "$APP_KEY" ] && [ -n "$APP_SECRET" ]; then
            echo "Running integration tests with real API..."
            python -m pytest tests/integration/ -v -m "not skip_ci"
          else
            echo "Skipping integration tests (no API credentials)"
          fi
